# Site settings
name: Less Or More
email: luoyan35714@126.com
author: Freud Kang
url: https://kassavatito.github.io/
resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/luoyan35714/
baseurl: "/"
description: Actually, less is more!
meta_description: sfsafsdf
motto: It's our wits that make us men.
banner: asfd

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: luoyan35714

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

